version: '3.4'

services:
  website:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  weatherforecast:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

