receivers:
    zipkin:
        endpoint: 0.0.0.0:9412
extensions:
    health_check:
    pprof:
        endpoint: :1888
    zpages:
        endpoint: :55679
exporters:
    logging:
        loglevel: debug
        sampling_initial: 5
        sampling_thereafter: 200

    azuremonitor:
        endpoint: "https://dc.services.visualstudio.com/v2/track"
        #instrumentation_key: "<INSTRUMENTATION-KEY>"
        instrumentation_key: ${APPLICATIONINSIGHTS_INSTRUMENTATION_KEY}

        # maxbatchsize is the maximum number of items that can be
        # queued before calling to the configured endpoint
        maxbatchsize: 1
        # maxbatchinterval is the maximum time to wait before calling
        # the configured endpoint.
        maxbatchinterval: 10s

    zipkin:
        endpoint: "http://zipkin:9411/api/v2/spans"

service:
    extensions: [pprof, zpages, health_check]
    pipelines:
        traces:
            receivers: [zipkin]
            exporters: [azuremonitor,logging,zipkin]