apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurekeyvault
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName # Required
    value: "dapr-demo-ali-kv"
  - name: azureEnvironment # Optional, defaults to AZUREPUBLICCLOUD
    value: "AZUREPUBLICCLOUD"

  - name: azureTenantId
    secretKeyRef:
        name: SP_TENANT
        key: SP_TENANT
  - name: azureClientId
    secretKeyRef:
        name: SP_APPID
        key: SP_APPID
  - name: azureClientSecret
    secretKeyRef:
        name: SP_PASSWORD
        key: SP_PASSWORD
auth:
    secretStore: envvar-secret-store